#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "thelounge"
name = "The Lounge"
description.en = "Web IRC client"
description.fr = "Client Web IRC"

version = "4.5.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://thelounge.chat/"
demo = "https://demo.thelounge.chat/"
admindoc = "https://thelounge.chat/docs"
code = "https://github.com/thelounge/thelounge"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = true
sso =  false

disk = "50M"
ram.build = "1500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/irc"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/thelounge/thelounge/archive/refs/tags/v4.5.2.tar.gz"
    sha256 = "81148db208ffdf056a5284147907b9d842ee0c35dfdde1c082379955f413a76a"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.nodejs]
    version = "24"
    