packaging_format = 2

id = "thelounge"
name = "The Lounge"
description.en = "Web IRC client"
description.fr = "Client Web IRC"

version = "4.3.1~ynh2"

maintainers = ["rafi59"]

[upstream]
license = "MIT"
website = "https://thelounge.chat/"
demo = "https://demo.thelounge.chat/"
admindoc = "https://thelounge.chat/docs"
code = "https://github.com/thelounge/thelounge"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = false
ldap = false
sso =  false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/irc"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/thelounge/thelounge/archive/v4.3.1.tar.gz"
        sha256 = "7bf444cc97449d78a74b35c3fea882ddf6e3df265f0e2252a23cc48309b11713"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
        [resources.apt.extras]
        repo = "deb https://dl.yarnpkg.com/debian/ stable main"
        key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
        packages = "yarn"
