packaging_format = 2

id = "thelounge"
name = "The Lounge"
description.en = "Web IRC client"
description.fr = "Client Web IRC"

version = "4.4.0~ynh1"

maintainers = ["rafi59"]

[upstream]
license = "MIT"
website = "https://thelounge.chat/"
demo = "https://demo.thelounge.chat/"
admindoc = "https://thelounge.chat/docs"
code = "https://github.com/thelounge/thelounge"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = false
ldap = false
sso =  false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/irc"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/thelounge/thelounge/archive/v4.4.0-pre.1.tar.gz"
        sha256 = "2530f4dd0da22fe557984baf90fab4e27cc0e64b91d6debf01860f2e395290fe"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt.extras]
    yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    yarn.packages = "yarn"
