#!/bin/bash

domain=$(sudo yunohost app setting thelounge domain)

sudo systemctl stop thelounge
sudo systemctl disable thelounge
sudo yunohost service remove thelounge

sudo rm -rf /var/www/thelounge
sudo rm -f /etc/nginx/conf.d/$domain.d/thelounge.conf
sudo rm -f /etc/systemd/system/thelounge.service

sudo userdel thelounge

sudo service nginx reload
sudo yunohost app ssowatconf
